export enum StatusMessage{
    SUCCESS="Operation Successful",
    CREATED="Resource created Successfully",
    BAD_REQUEST="Bad Request, Check URL !",
    UNAUTHORIZED="Unauhorized Access",
    FORBIDDEN = "Access forbidden",
    NOT_FOUND="Resource not Found",
    INTERNAL_SERVER_ERROR="An Internal server Error",
    INVALID_CREDENTIALS= " Invalid credentials",
    ERROR= " Error Occured !",
    INVALID="Incorrect Password !!",
    BLOCKED="User is Blocked !!",
    CONFLICT="Already Exist !",
    DELETED="REsource deleted !",
    PASSWORD_RESET_SUCCESS="Password reset succesful !",
    OLD_PASSWORD_INCORRECT ="Old Password Incorrect",
    PASSWORD_MISMATCH="New Password and Confirm Password do not match !",
    USER_NOT_FOUND="User not found !",
    PASSWORD_RESET_FAILED="Password reset failed !",
    UPDATE_SUCCESS="Update Successful",
    UPDATE_FAILED="Update Failed",
    CANCEL_BOOKING="Booking cannot be cancelled !",
    MISSING_REQUIRED_FIELD="Values not found !",
}